"""Export the trained Poly-2 Ridge surrogate weights to a Rust source file.

Trains the same `Poly-2 Ridge` pipeline that lives in
`src/aerosurrogate/models.py` on the cached NeuralFoil-labeled dataset
(`data/aero_dataset.csv`), then dumps:

  * StandardScaler `mean_` and `scale_` (length 11)
  * PolynomialFeatures expansion as a list of (i, j) index pairs of length 66
    (interactions + squares of the 11 raw features, no bias)
  * Ridge `coef_` and `intercept_` for each of (CL, CD, CM)

into `rust/aerosurrogate-core/src/surrogate/ridge.rs` as `pub const` arrays.

Run with::

    PYTHONPATH=src python rust/scripts/export_ridge_weights.py

The output `ridge.rs` is committed to the repo so `cargo build` is hermetic.
Re-running this script is part of the dataset-rebuild workflow.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
from sklearn.linear_model import Ridge
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

from aerosurrogate.dataset import load_dataset, split_by_airfoil
from aerosurrogate.models import FEATURES

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_PATH = REPO_ROOT / "rust" / "aerosurrogate-core" / "src" / "surrogate" / "ridge.rs"


def train_one(target: str, df) -> tuple[Pipeline, np.ndarray, np.ndarray]:
    train_df, _test_df, _meta = split_by_airfoil(df, test_frac=0.2)
    x = train_df[FEATURES].to_numpy()
    y = train_df[target].to_numpy()
    pipe = Pipeline([
        ("scaler", StandardScaler()),
        ("poly", PolynomialFeatures(degree=2, include_bias=False)),
        ("model", Ridge(alpha=1.0)),
    ])
    pipe.fit(x, y)
    return pipe, x, y


def fmt_floats(values, indent: str = "    ") -> str:
    chunks = []
    for i, v in enumerate(values):
        prefix = "\n" + indent if i % 4 == 0 else " "
        chunks.append(f"{prefix}{float(v): .17e},")
    return "".join(chunks).rstrip(",")


def main() -> None:
    df = load_dataset()
    pipes = {tgt: train_one(tgt, df) for tgt in ["CL", "CD", "CM"]}

    # The scaler / poly are identical across all three targets (same x_train);
    # take them from any one.
    pipe_cl, x_train, _y_cl = pipes["CL"]
    scaler: StandardScaler = pipe_cl.named_steps["scaler"]
    poly: PolynomialFeatures = pipe_cl.named_steps["poly"]

    n_features = len(FEATURES)
    assert scaler.mean_.shape == (n_features,)
    assert scaler.scale_.shape == (n_features,)

    # poly.powers_ has shape (n_output_features, n_input_features) and is
    # all zeros except a 1 (or 2 for squares) on the active feature(s).
    # We can encode each output as a (i, j) index pair: i for linear, j for
    # the other side of an interaction. For a square term i = j.
    # Encode each polynomial output as a tagged term:
    #   kind == 0  → linear:        value = x_i          (i==j, ignore j)
    #   kind == 1  → square:        value = x_i · x_i    (i==j)
    #   kind == 2  → interaction:   value = x_i · x_j    (i!=j)
    powers = poly.powers_
    poly_indices: list[tuple[int, int]] = []
    kinds: list[int] = []
    for row in powers:
        actives = np.flatnonzero(row)
        if len(actives) == 1 and row[actives[0]] == 1:
            i = int(actives[0])
            poly_indices.append((i, i))
            kinds.append(0)  # linear
        elif len(actives) == 1 and row[actives[0]] == 2:
            i = int(actives[0])
            poly_indices.append((i, i))
            kinds.append(1)  # square
        elif len(actives) == 2:
            i, j = int(actives[0]), int(actives[1])
            poly_indices.append((i, j))
            kinds.append(2)  # interaction
        else:
            raise RuntimeError(f"unexpected poly row: {row}")

    n_poly = len(poly_indices)
    coefs = {tgt: pipe.named_steps["model"].coef_ for tgt, (pipe, _, _) in pipes.items()}
    intercepts = {tgt: float(pipe.named_steps["model"].intercept_) for tgt, (pipe, _, _) in pipes.items()}
    for tgt, c in coefs.items():
        assert c.shape == (n_poly,), (tgt, c.shape, n_poly)

    out = []
    out.append(
        "//! Baked-in Poly-2 Ridge surrogate weights.\n"
        "//!\n"
        "//! AUTO-GENERATED by `rust/scripts/export_ridge_weights.py`. Do not edit by hand.\n"
        "//! Trained on `data/aero_dataset.csv` (15,334 NeuralFoil-labeled airfoil samples).\n"
        "\n"
        "// The bulk of this file is `pub const` weight arrays; documenting each one\n"
        "// individually adds no value over the module docstring above. Silence the\n"
        "// crate-wide `missing_docs` lint locally instead.\n"
        "#![allow(missing_docs)]\n"
    )
    out.append("/// Number of raw geometric+flow features the surrogate consumes.")
    out.append(f"pub const N_FEATURES: usize = {n_features};\n")
    out.append("/// Number of polynomial-expansion features after `PolynomialFeatures(degree=2)`.")
    out.append(f"pub const N_POLY_FEATURES: usize = {n_poly};\n")

    out.append("/// `StandardScaler.mean_` for the raw features.")
    out.append(
        f"pub const SCALER_MEAN: [f64; {n_features}] = ["
        + fmt_floats(scaler.mean_)
        + "\n];\n"
    )
    out.append("/// `StandardScaler.scale_` for the raw features.")
    out.append(
        f"pub const SCALER_SCALE: [f64; {n_features}] = ["
        + fmt_floats(scaler.scale_)
        + "\n];\n"
    )

    out.append("/// Polynomial-expansion index pairs `(i, j)` — i==j for squares.")
    out.append(f"pub const POLY_INDICES: [(u8, u8); {n_poly}] = [")
    for i, j in poly_indices:
        out.append(f"    ({i}, {j}),")
    out.append("];\n")
    out.append("/// Per-term kind tag: 0 = linear `x_i`, 1 = square `x_i²`, 2 = interaction `x_i·x_j`.")
    out.append(f"pub const POLY_KIND: [u8; {n_poly}] = [")
    for k in range(0, n_poly, 16):
        out.append("    " + ", ".join(str(v) for v in kinds[k : k + 16]) + ",")
    out.append("];\n")

    for tgt in ["CL", "CD", "CM"]:
        out.append(f"/// Ridge coefficients for `{tgt}` (length {n_poly}).")
        out.append(
            f"pub const RIDGE_COEF_{tgt}: [f64; {n_poly}] = ["
            + fmt_floats(coefs[tgt])
            + "\n];"
        )
        out.append(f"/// Ridge intercept for `{tgt}`.")
        out.append(f"pub const RIDGE_INTERCEPT_{tgt}: f64 = {intercepts[tgt]: .17e};\n")

    # Trained-pipeline cross-check fixture (small, in-source).
    sample_x = x_train[:5]
    out.append("/// Five (features, predicted_cl, cd, cm) rows for a static parity test.")
    out.append("/// `SAMPLE_X[k]` = raw 11-feature input; `SAMPLE_CL/CD/CM[k]` = sklearn output.")
    out.append(f"pub const N_SAMPLES: usize = {len(sample_x)};")
    out.append(f"pub const SAMPLE_X: [[f64; {n_features}]; {len(sample_x)}] = [")
    for row in sample_x:
        out.append("    [" + ", ".join(f"{v: .17e}" for v in row) + "],")
    out.append("];")
    for tgt in ["CL", "CD", "CM"]:
        preds = pipes[tgt][0].predict(sample_x)
        out.append(
            f"pub const SAMPLE_{tgt}: [f64; {len(sample_x)}] = ["
            + ", ".join(f"{float(v): .17e}" for v in preds)
            + "];"
        )
    out.append("")

    # ---- the predict() inference function ---------------------------------
    out.append(
        """
/// Standardize a raw feature vector, polynomial-expand, and apply the Ridge
/// dot-product for a single target. Pure scalar arithmetic; no allocation.
#[inline]
fn predict_one(
    features: &[f64; N_FEATURES],
    coef: &[f64; N_POLY_FEATURES],
    intercept: f64,
) -> f64 {
    // Standard-scale: x' = (x − μ) / σ
    let mut scaled = [0.0_f64; N_FEATURES];
    for k in 0..N_FEATURES {
        scaled[k] = (features[k] - SCALER_MEAN[k]) / SCALER_SCALE[k];
    }
    // Poly-2 expand + dot-product with Ridge coefficients.
    let mut acc = intercept;
    for t in 0..N_POLY_FEATURES {
        let (i, j) = POLY_INDICES[t];
        let xi = scaled[i as usize];
        let xj = scaled[j as usize];
        let term = match POLY_KIND[t] {
            0 => xi,             // linear x_i
            1 => xi * xi,        // square x_i²
            _ => xi * xj,        // interaction x_i · x_j
        };
        acc += coef[t] * term;
    }
    acc
}

/// Predicted (Cl, Cd, Cm) at one raw feature vector.
#[derive(Debug, Clone, Copy)]
pub struct RidgePrediction {
    /// Lift coefficient prediction.
    pub cl: f64,
    /// Drag coefficient prediction.
    pub cd: f64,
    /// Pitching-moment coefficient prediction.
    pub cm: f64,
}

/// Apply the Poly-2 Ridge surrogate to a single 11-feature input.
///
/// The 11 features are (in order):
///   max_camber, camber_pos, max_thickness, le_radius, te_angle_deg,
///   thickness_25, thickness_50, thickness_75, alpha_deg, log10_Re, n_crit.
#[inline]
pub fn predict(features: &[f64; N_FEATURES]) -> RidgePrediction {
    RidgePrediction {
        cl: predict_one(features, &RIDGE_COEF_CL, RIDGE_INTERCEPT_CL),
        cd: predict_one(features, &RIDGE_COEF_CD, RIDGE_INTERCEPT_CD),
        cm: predict_one(features, &RIDGE_COEF_CM, RIDGE_INTERCEPT_CM),
    }
}
"""
    )

    OUT_PATH.write_text("\n".join(out))
    print(f"wrote {OUT_PATH}")
    print(f"  n_features={n_features}  n_poly={n_poly}")
    for tgt in ["CL", "CD", "CM"]:
        preds = pipes[tgt][0].predict(sample_x)
        print(f"  sklearn {tgt}: {[f'{p:.4f}' for p in preds[:3]]}")


if __name__ == "__main__":
    main()
