//! Baked-in GradientBoosting surrogate.
//!
//! Auto-generated by `rust/scripts/export_gbm_weights.py`. Until that
//! script is run the file is a stub; the surrogate-using sections will
//! return `unimplemented!()`.

/// Flat representation of a decision-tree node. Internal nodes set
/// `feature`/`threshold` and use `left`/`right`; leaves set `feature = u16::MAX`
/// and `value`.
#[derive(Debug, Clone, Copy)]
pub struct GbmNode {
    /// Split feature index; `u16::MAX` flags a leaf.
    pub feature: u16,
    /// Left child index (into the flat node array).
    pub left: u32,
    /// Right child index (into the flat node array).
    pub right: u32,
    /// Split threshold for an internal node, leaf value for a leaf.
    pub threshold_or_value: f64,
}
