//! Baked-in sklearn airfoil surrogates.
//!
//! Two surrogate models from the Python `aerosurrogate.models` zoo are
//! exported to pure-Rust const arrays so the lifting-line solver can run
//! without any Python / sklearn / PyTorch dependency at runtime:
//!
//! * [`ridge`] — Poly-2 Ridge pipeline (66 features after polynomial
//!   expansion, scalar coefficients).
//! * [`gbm`] — GradientBoosting (600 trees × depth 4, flat tree-node arrays).
//!
//! Both files are auto-generated by `rust/scripts/export_{ridge,gbm}_weights.py`
//! and committed to the repo so `cargo build` is hermetic. The build is not
//! coupled to Python at any point.

pub mod gbm;
pub mod ridge;
